---
- hosts: all
  become: true
  tasks:
    - name: Disable selinux
      selinux:
        policy: targeted
        state: permissive
    - name: Add k8s repo
      template:
        src: ../templates/k8s.repo.j2
        dest: /etc/yum.repos.d/k8s.repo
    - name: Add k8s prereq packages
      yum:
      #dnf:
        state: present
        name: "{{ item }}"
      with_items:
        - docker
        - iproute
        #- iproute-tc
        - kubeadm
        - kubelet
    - name: Enable kubelet
      systemd:
        service: kubelet
        state: started
        enabled: true
    - name: Enable docker
      systemd:
        service: docker
        state: started
        enabled: true
    - name: Install kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.7.2/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0755
    - name: Enable net bridge iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    - name: Enable net bridge ip6tables
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes

    #- name: Increase root LV to 5 GB
    #  command: lvresize -L 5G atomicos/root
    #  ignore_errors: true
    #- name: Resize root file system
    #  command: xfs_growfs /dev/mapper/atomicos-root
    #- name: Make sure all interfaces are up
    #  systemd:
    #    name=network
    #    state=restarted
    #- name: Refresh facts
    #  setup:
    #- name: build hosts file
    #  lineinfile:
    #    dest=/etc/hosts
    #    regexp='.*{{ item }}$'
    #    line="{{ hostvars[item].ansible_eth0.ipv4.address }} {{item}}"
    #    state=present
    #  when: hostvars[item].ansible_eth0.ipv4.address is defined
    #  with_items: "{{ groups['all'] }}"
    #- name: Add 'registry' dns name
    #  lineinfile:
    #    dest=/etc/hosts
    #    regexp='.*registry$'
    #    line="192.168.121.1 registry"
    #    state=present
    #- name: Allow 'registry' as insecure registry
    #  lineinfile:
    #    dest=/etc/sysconfig/docker
    #    regexp='.*INSECURE_REGISTRY'
    #    line='INSECURE_REGISTRY="--insecure-registry=192.168.0.0/16"'
    #    state=present
    #- name: Restart docker
    #  systemd:
    #    name=docker
    #    state=restarted
