---

- hosts: master
  become: true
  vars:
    k8s_init_token: "000000.1111111111111111"
  tasks:
    - name: Init on master
      command: kubeadm init --token {{ k8s_init_token }} creates=/etc/kubernetes/admin.conf
    - name: Create /root/.kube
      file:
        path: /root/.kube
        state: directory
    - name: Create .kube config (root)
      copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
    - name: Create /home/vagrant/.kube
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
    - name: Create .kube config (vagrant)
      copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
    - name: Apply a pod network
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    - name: Get DNS address
      shell: kubectl get services --all-namespaces | grep kube-dns | awk "{print \$3}"
      register: dnsaddr
    - name: Wait for DNS to be ready
      wait_for: host={{ dnsaddr.stdout }} port=53 state=started timeout=600

- hosts: workers
  vars:
    k8s_init_token: "000000.1111111111111111"
  become: true
  tasks:
    - name: Join on workers
      command: kubeadm join --skip-preflight-checks --token {{ k8s_init_token }} master:6443
    - name: wait for node to be ready
      shell: test "$(kubectl get nodes {{ ansible_hostname }} --no-headers | awk '{ print $2 }')" = "Ready"
      register: task_result
      until: task_result.rc == 0
      delay: 10
      retries: 60
      changed_when: false

#- hosts: master
#  tasks:
#  - name: Deploy dashboard
#    command: kubectl create -f https://git.io/kube-dashboard
