---
# Upgrades fedora and automatically reboots if an upgrade was applied
- hosts: all
  become: true
  tasks:
    - name: Upgrade system
      dnf:
        name: "*"
        state: latest
      register: upgrade
    - name: Install selinux-python
      dnf:
        name: libselinux-python
        state: present
    - name: Restart if upgraded
      shell: sleep 2 && systemctl reboot
      async: 1
      poll: 0
      when: upgrade.changed == true
    - name: Wait for host to be available after reboot
      local_action: wait_for
      args:
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        port: "{{ ansible_ssh_port }}"
        search_regex: OpenSSH
        delay: 3
      when: upgrade.changed == true
